config/routes.rb
LaundryAlert::Application.routes.draw do
  root 'accounts#new'
  post 'twilio/process_sms', :to => 'twilio#process_sms'
  get 'check_em', :to => 'worker#go'
  post '/login',  :to => 'accounts#login'

  resource :account
  resources :runs, :only => [:show]
end

app/models/account.rb
class Account < ActiveRecord::Base

  validates :phone, :access_token, :core_id,
    :presence => true

  validates :phone, :length => {:is => 10}

  before_validation :strip_phone

  has_many :runs

  scope :watching, -> { where(:watching => true) }

  def core
    @core ||= RubySpark::Tinker.new(core_id, access_token)
  end

  def display_phone
    "(#{phone[0,3]}) #{phone[3,3]}-#{phone[6,4]}"
  end

  def twilio_phone
    "+1" + phone
  end

  def watch(machine_type)
    runs.create(:machine_type => machine_type)
    update_attributes(:watching => true)
  end

  def get_data
    reading = core.variable("lastminute")
    latest_run.add(reading)
  rescue
  end

  def configure
    # do something with latest_run
  end

  # private

  def latest_run
    @latest_run ||= runs.last
  end

  def strip_phone
    self.phone = phone.gsub(/[^0-9]/, "") if phone?
  end
end

app/models/run.rb
class Run < ActiveRecord::Base
  belongs_to :account

  validates :account, :machine_type, :presence => true
  validates :machine_type, :inclusion => { :in => %w(washer dryer) }

  scope :by_date, -> { order('created_at DESC') }

  def to_s
    created_at.strftime("#{machine_type.capitalize} - %b %_d, %_I:%M %P")
  end

  def add(reading)
    data_set = raw_data
    data_set += [reading]

    update_attributes(:data => data_set.join(","))
  end

  def finished?
    LaundryAlert::FinishChecker.finished?(self)
  end

  def raw_data
    @raw_data ||= begin
      data.present? ? data.split(",").map(&:to_i) : []
    end
  end

  def washer?
    machine_type == 'washer'
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :assign_account, :only => [:show, :edit, :update]

  def new
    redirect_to '/account' if logged_in?

    @account = Account.new
  end

  def create
    @account = Account.new(account_params)

    if @account.save
      cookies.permanent[:account_id] = @account.id
      redirect_to '/account'
    else
      render :new
    end
  end

  def login
    phone = params[:existing_account][:phone].gsub(/[^0-9]/, "")

    if account = Account.find_by_phone(phone)
      cookies.permanent[:account_id] = account.id
      redirect_to '/account'
    else
      redirect_to root_url
    end
  end

  def show
    redirect_to '/' unless logged_in?
  end

  def edit
  end

  def update
    if @account.update_attributes(account_params)
      redirect_to '/account'
    else
      render :edit
    end
  end

  # private

  def logged_in?
    current_account.present?
  end

  def current_account
    Account.find(cookies[:account_id]) if cookies[:account_id]
  rescue
    cookies[:account_id] = nil
    return false
  end

  def assign_account
    @account = current_account
  end

  def account_params
    params[:account].permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  def show
    @run = Run.find(params[:id])
    render :show, :layout => false
  end
end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController
  skip_before_action :verify_authenticity_token

  def process_sms
    if account = Account.find_by_phone(params[:From][2,10])
      handler = LaundryAlert::TextHandler.new(account, params[:Body])
      @response = handler.response
    else
      @response = "Looks like you're not signed up on http://laundryalert.herokuapp.com."
    end

    render 'response.xml.erb', :content_type => 'text/xml'
  end

end

app/controllers/worker_controller.rb
class WorkerController < ApplicationController

  def go
    LaundryAlert::Worker.do_work

    render :nothing => true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for @account, :url => account_path do |f| %>
  <%= f.label :phone, "* Phone Number" %>
  <%= f.input :phone, :label => false, :input_html => {:maxlength => 20, :class => 'form-control'} %>

  <%= f.label :access_token, "* Access Token" %>
  <%= f.input :access_token, :label => false, :input_html => {:class => 'form-control'} %>

  <%= f.label :core_id, "* Core ID" %>
  <%= f.input :core_id, :label => false, :input_html => {:class => 'form-control'} %>

  <%= f.label :high_threshold, "High Threshold" %>
  <%= f.input :high_threshold, :label => false, :input_html => {:class => 'form-control'} %>

  <%= f.label :low_threshold, "Low Threshold" %>
  <%= f.input :low_threshold, :label => false, :input_html => {:class => 'form-control'} %>
  <br>
  <div class="btn-group-vertical">
    <%= f.submit "Submit", :class => 'btn btn-success wide' %>
    <% if @account.persisted? %>
      <%= link_to "Cancel", :back, :class => "btn btn-danger wide" %>
    <% end %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<%= content_for :title, "Edit your Info" %>

<%= render "form" %>

app/views/accounts/new.html.erb
<%= content_for :title, "Register your Core and Phone Number" %>

<%= render "form" %>

<hr>

<h3 class='thin'>Or login with your existing account</h3>
<br>
<%= simple_form_for :existing_account, :url => login_path do |f| %>
  <%= f.label :phone, "* Phone Number" %>
  <%= f.input :phone, :label => false, :input_html => {:maxlength => 20, :class => 'form-control'} %>
  <br>
  <%= f.submit "Login", :class => 'btn btn-primary wide' %>

<% end %>

app/views/accounts/show.html.erb
<%= content_for :title, "Your Info" %>

<div class="info">
  <h4>Phone</h4>
  <%= @account.display_phone %>
</div>

<div class="info">
  <h4>Access Token</h4>
  <%= @account.access_token %>
</div>

<div class="info">
  <h4>Core ID</h4>
  <%= @account.core_id %>
</div>

<div class="info">
  <h4>Runs</h4>
  <ul style="list-style:none; margin: 0; padding: 0;">
    <% @account.runs.by_date.each do |run| %>
      <li><%= link_to run, run %></li>
    <% end %>
  </ul>
</div>

<%= link_to "Edit Info", edit_account_path, :class => 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LaundryAlert</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=320;">
</head>
<body>

<div class="center">
  <h3 class="no-margin"><%= content_for(:title) %></h3>
  <hr>

  <%= yield %>
</div>

<%= javascript_include_tag "application" %>

</body>
</html>

app/views/runs/show.html.erb
<%= javascript_include_tag "application" %>
<%= stylesheet_link_tag "application" %>

<div class="graph-page">
  <div><%= link_to "Back", root_url, :class => 'btn btn-primary btn-graph' %>
  <div id="container"></div>

  <script>
    var $container = $("#container")

    new Highcharts.Chart({
      chart: {
        backgroundColor: '#eee',
        height: 700,
        renderTo: 'container'
      },
      title: { text: '' },
      yAxis: [{
          title: { text: 'Reading' },
          min: 0,
          plotLines: [
            {
              color: '#FF0000',
              width: 2,
              value: <%= @run.account.high_threshold %>
            },
            {
              color: '#0000FF',
              width: 2,
              value: <%= @run.account.low_threshold %>
            }
          ]
      }],
      xAxis: {
        title: { text: 'Minutes' },
        min: 0
      },
      series: [
        {
          name: "Run",
          pointInterval: 1,
          pointStart: 0,
          data: [<%= @run.data %>]
        }
      ]
    });
  </script>
</div>

app/views/twilio/response.xml.erb
<Response>
  <Sms><%= @response %></Sms>
</Response>